name: Generate Snake Game
on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight to update daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Snake Game
      uses: Platane/snk@master
      with:
        github_user_name: evalieve
        svg_out_path: dist/github-contribution-grid-snake.svg

    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: main # or master, depending on your default branch
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
